Repository RedStarMC/Wiki, pull requests merged in 2025-07, with the labels that each got.

#73 feat: 加入我们和生存服介绍/指引
  admin/Wiki 编辑日志.md
  docs/server-introduce/introduction-to-survival-server.md
Labels: 📖文档, ➕增强

#74 管理组职位变更: 游俊卿从协管提升为管理
  admin/Wiki 编辑日志.md
  docs/admin-group.md
  release/intro.md
Labels: 📖文档, ➕增强

#75 创建 CONTRIBUTING
  CONTRIBUTING.md
Labels: ➕增强

#76 [Snyk] Upgrade @docusaurus/faster from 3.7.0 to 3.8.1
  package-lock.json
  package.json
Labels: dependencies, ➕增强

#77 [Snyk] Upgrade @docusaurus/theme-common from 3.7.0 to 3.8.1
  package-lock.json
  package.json
Labels: dependencies

#84 [Snyk] Fix for 2 vulnerabilities
  package-lock.json
  package.json
Labels: dependencies

#88 feat: 其他玩法 fix: 玩法错误
  docs/server-introduce/_images/budding.png
  docs/server-introduce/_images/en_gold_apple.png
  docs/server-introduce/_images/totem.png
  docs/server-introduce/introduction-to-survival-server.md
Labels: 📖文档, ➕增强

#89 添加生存服群的链接
  docs/intro.md
  docs/server-introduce/_images/budding.png
  docs/server-introduce/_images/en_gold_apple.png
  docs/server-introduce/_images/totem.png
Labels: 📖文档

#91 feat: 登录服页面 perf: 生存服介绍和新手入门
  admin/Wiki 编辑日志.md
  docs/getting-started/_images/tip.txt
  docs/getting-started/getting-started.md
  docs/how-to-join-server.md
  docs/intro.md
  docs/server-introduce/introduction-to-survival-server.md
  docs/server-introduce/login-comands.md
Labels: 📖文档, ➕增强

#92 feat: 更新其人志，生存服介绍添加连锁采集
  admin/Wiki 编辑日志.md
  docs/server-introduce/introduction-to-survival-server.md
  renwu/intro.md
  renwu/pingguo.md
Labels: 📖文档, ➕增强

#93 规则和运营规范
  admin/运营规范/_category_.json
  admin/运营规范/_images/tip.txt
  admin/运营规范/活动策划流程.md
  admin/运营规范/管理审核流程.md
  docs/rules/player-notice.md
  docs/rules/申诉、举报与声明.md
Labels: 📖文档, 👋修复, ➕增强
